-- load_tables.sql
-- Generated by build_kent_hotspots_fixed_window_urban_rural_final.py
-- Run after creating the PostgreSQL schema.
BEGIN;

\copy local_authorities (la_id, la_code, la_name, authority_type, is_kcc_highway_authority) FROM '/Users/amritpalsandhu/Downloads/kent_hotspot_output/local_authorities.csv' WITH (FORMAT csv, HEADER true);
\copy road_classes (road_class_id, road_class_code, road_class_label) FROM '/Users/amritpalsandhu/Downloads/kent_hotspot_output/road_classes.csv' WITH (FORMAT csv, HEADER true);
\copy junction_types (junction_id, junction_code, junction_label) FROM '/Users/amritpalsandhu/Downloads/kent_hotspot_output/junction_types.csv' WITH (FORMAT csv, HEADER true);
\copy lighting_conditions (lighting_id, lighting_code, lighting_label) FROM '/Users/amritpalsandhu/Downloads/kent_hotspot_output/lighting_conditions.csv' WITH (FORMAT csv, HEADER true);
\copy road_surface_types (surface_id, surface_code, surface_label) FROM '/Users/amritpalsandhu/Downloads/kent_hotspot_output/road_surface_types.csv' WITH (FORMAT csv, HEADER true);
\copy weather_conditions (weather_id, weather_code, weather_label) FROM '/Users/amritpalsandhu/Downloads/kent_hotspot_output/weather_conditions.csv' WITH (FORMAT csv, HEADER true);
\copy vehicle_categories (vehicle_category_id, category_code, category_label) FROM '/Users/amritpalsandhu/Downloads/kent_hotspot_output/vehicle_categories.csv' WITH (FORMAT csv, HEADER true);
\copy vehicle_types (vehicle_type_id, vehicle_code, vehicle_label, vehicle_category_id) FROM '/Users/amritpalsandhu/Downloads/kent_hotspot_output/vehicle_types.csv' WITH (FORMAT csv, HEADER true);
\copy casualty_classes (casualty_class_id, class_code, class_label) FROM '/Users/amritpalsandhu/Downloads/kent_hotspot_output/casualty_classes.csv' WITH (FORMAT csv, HEADER true);
\copy casualty_types (casualty_type_id, casualty_code, casualty_label, is_vru) FROM '/Users/amritpalsandhu/Downloads/kent_hotspot_output/casualty_types.csv' WITH (FORMAT csv, HEADER true);
\copy accident_records (accident_id, accident_index, la_id, road_class_id, junction_id, lighting_id, surface_id, weather_id, accident_date, accident_time, day_of_week, accident_severity, number_of_vehicles, number_of_casualties, road_reference, speed_limit, urban_rural, latitude, longitude) FROM '/Users/amritpalsandhu/Downloads/kent_hotspot_output/accident_records.csv' WITH (FORMAT csv, HEADER true);
\copy vehicle_records (vehicle_id, accident_id, vehicle_type_id, vehicle_sequence, driver_age_band, driver_sex, skidding_overturning) FROM '/Users/amritpalsandhu/Downloads/kent_hotspot_output/vehicle_records.csv' WITH (FORMAT csv, HEADER true);
\copy casualty_records (casualty_id, accident_id, casualty_class_id, casualty_type_id, casualty_sequence, vehicle_sequence, casualty_severity, casualty_age_band, casualty_sex) FROM '/Users/amritpalsandhu/Downloads/kent_hotspot_output/casualty_records.csv' WITH (FORMAT csv, HEADER true);
\copy analysis_runs (analysis_run_id, run_timestamp, source_dataset, source_year_start, source_year_end, police_force_code, cluster_method, cluster_epsilon_m, min_cluster_size, fatal_weight, serious_weight, slight_weight, notes) FROM '/Users/amritpalsandhu/Downloads/kent_hotspot_output/analysis_runs.csv' WITH (FORMAT csv, HEADER true);
\copy hotspot_locations (hotspot_id, analysis_run_id, cluster_id, la_id, road_class_id, road_reference, speed_limit, urban_rural, centroid_latitude, centroid_longitude) FROM '/Users/amritpalsandhu/Downloads/kent_hotspot_output/hotspot_locations.csv' WITH (FORMAT csv, HEADER true);
\copy accident_hotspot_membership (analysis_run_id, hotspot_id, accident_id, distance_to_centroid_m) FROM '/Users/amritpalsandhu/Downloads/kent_hotspot_output/accident_hotspot_membership.csv' WITH (FORMAT csv, HEADER true);

COMMIT;
